name: 15 - GitHub OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ROLE_ARN: arn:aws:iam::392938852724:role/15-github-oidc-oidc

jobs:
  verify-oidc:
    name: Verify AWS identity
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-oidc-lab

      - name: Verify assumed identity
        run: aws sts get-caller-identity